baseurl = "http://sethammons.com/"
languageCode = "en-us"
title = "Seth Ammons"
copyright = "Copyright (c) 2001 - 2014, Seth Ammons; all rights reserved."

pygmentsuseclasses = true
#pygmentsstyle = "github"

[author]
    name = "Seth Ammons"
    github = "sethgrid"
    linkedin = "sethammons"
    #facebook = "YOUR FB ID"
    #gaID = "YOUR Google Analytics Tracking ID"
    twitter = "seth_ammons"